language: python

python:
- 3.9

#services:
#  - docker

env:
  - Django=4.0.4

before_install:
- pip install poetry
#- docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.9-management

install:
- poetry install

script:
- poetry run flake8 .