# Generated by Django 4.0.1 on 2022-01-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventorization_service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
