# Generated by Django 4.0.4 on 2022-05-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorization_service', '0005_alter_item_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fix_status',
            field=models.CharField(choices=[('broken', 'Broken'), ('ok', 'OK')], default='ok', max_length=30),
        ),
    ]
