# Generated by Django 4.0.4 on 2022-05-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorization_service', '0007_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fix_status',
            field=models.CharField(choices=[('broken', 'Broken'), ('unfixable', 'Unfixable'), ('ok', 'OK')], default='ok', max_length=30),
        ),
    ]
